package ch.pproject.cookbook.shared.ingredient;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.ingredient.IngredientSearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class IngredientSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Ingredient getIngredient() {
    return getFieldByClass(Ingredient.class);
  }

  public static class Ingredient extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
