package ch.pproject.cookbook.shared.ingredient;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.ingredient.IngredientsTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class IngredientsTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public IngredientsTableRowData addRow() {
    return (IngredientsTableRowData) super.addRow();
  }

  @Override
  public IngredientsTableRowData addRow(int rowState) {
    return (IngredientsTableRowData) super.addRow(rowState);
  }

  @Override
  public IngredientsTableRowData createRow() {
    return new IngredientsTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return IngredientsTableRowData.class;
  }

  @Override
  public IngredientsTableRowData[] getRows() {
    return (IngredientsTableRowData[]) super.getRows();
  }

  @Override
  public IngredientsTableRowData rowAt(int index) {
    return (IngredientsTableRowData) super.rowAt(index);
  }

  public void setRows(IngredientsTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class IngredientsTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String ingredientNr = "ingredientNr";
    public static final String ingredient = "ingredient";
    public static final String measure = "measure";
    private Long m_ingredientNr;
    private String m_ingredient;
    private String m_measure;

    public Long getIngredientNr() {
      return m_ingredientNr;
    }

    public void setIngredientNr(Long newIngredientNr) {
      m_ingredientNr = newIngredientNr;
    }

    public String getIngredient() {
      return m_ingredient;
    }

    public void setIngredient(String newIngredient) {
      m_ingredient = newIngredient;
    }

    public String getMeasure() {
      return m_measure;
    }

    public void setMeasure(String newMeasure) {
      m_measure = newMeasure;
    }
  }
}
