package ch.pproject.cookbook.shared.ingredient;

import java.util.Set;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.ingredient.IngredientForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class IngredientFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  /**
   * access method for property IngredientNr.
   */
  public Long getIngredientNr() {
    return getIngredientNrProperty().getValue();
  }

  /**
   * access method for property IngredientNr.
   */
  public void setIngredientNr(Long ingredientNr) {
    getIngredientNrProperty().setValue(ingredientNr);
  }

  public IngredientNrProperty getIngredientNrProperty() {
    return getPropertyByClass(IngredientNrProperty.class);
  }

  public Measure getMeasure() {
    return getFieldByClass(Measure.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public static class IngredientNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Measure extends AbstractValueFieldData<Set<Long>> {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
