package ch.pproject.cookbook.shared.recipe.ingredient;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.recipe.ingredient.RecipeIngredientsTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RecipeIngredientsTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public RecipeIngredientsTableRowData addRow() {
    return (RecipeIngredientsTableRowData) super.addRow();
  }

  @Override
  public RecipeIngredientsTableRowData addRow(int rowState) {
    return (RecipeIngredientsTableRowData) super.addRow(rowState);
  }

  @Override
  public RecipeIngredientsTableRowData createRow() {
    return new RecipeIngredientsTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return RecipeIngredientsTableRowData.class;
  }

  @Override
  public RecipeIngredientsTableRowData[] getRows() {
    return (RecipeIngredientsTableRowData[]) super.getRows();
  }

  @Override
  public RecipeIngredientsTableRowData rowAt(int index) {
    return (RecipeIngredientsTableRowData) super.rowAt(index);
  }

  public void setRows(RecipeIngredientsTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class RecipeIngredientsTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String recipeIngredientNr = "recipeIngredientNr";
    public static final String ingredientNr = "ingredientNr";
    public static final String quantity = "quantity";
    public static final String measure = "measure";
    public static final String name = "name";
    private Long m_recipeIngredientNr;
    private Long m_ingredientNr;
    private BigDecimal m_quantity;
    private Long m_measure;
    private String m_name;

    public Long getRecipeIngredientNr() {
      return m_recipeIngredientNr;
    }

    public void setRecipeIngredientNr(Long newRecipeIngredientNr) {
      m_recipeIngredientNr = newRecipeIngredientNr;
    }

    public Long getIngredientNr() {
      return m_ingredientNr;
    }

    public void setIngredientNr(Long newIngredientNr) {
      m_ingredientNr = newIngredientNr;
    }

    public BigDecimal getQuantity() {
      return m_quantity;
    }

    public void setQuantity(BigDecimal newQuantity) {
      m_quantity = newQuantity;
    }

    public Long getMeasure() {
      return m_measure;
    }

    public void setMeasure(Long newMeasure) {
      m_measure = newMeasure;
    }

    public String getName() {
      return m_name;
    }

    public void setName(String newName) {
      m_name = newName;
    }
  }
}
