package ch.pproject.cookbook.shared.recipe.ingredient;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.recipe.ingredient.RecipeIngredientForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RecipeIngredientFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Ingredient getIngredient() {
    return getFieldByClass(Ingredient.class);
  }

  public Measure getMeasure() {
    return getFieldByClass(Measure.class);
  }

  public Quantity getQuantity() {
    return getFieldByClass(Quantity.class);
  }

  /**
   * access method for property RecipeIngredientNr.
   */
  public Long getRecipeIngredientNr() {
    return getRecipeIngredientNrProperty().getValue();
  }

  /**
   * access method for property RecipeIngredientNr.
   */
  public void setRecipeIngredientNr(Long recipeIngredientNr) {
    getRecipeIngredientNrProperty().setValue(recipeIngredientNr);
  }

  public RecipeIngredientNrProperty getRecipeIngredientNrProperty() {
    return getPropertyByClass(RecipeIngredientNrProperty.class);
  }

  /**
   * access method for property RecipeNr.
   */
  public Long getRecipeNr() {
    return getRecipeNrProperty().getValue();
  }

  /**
   * access method for property RecipeNr.
   */
  public void setRecipeNr(Long recipeNr) {
    getRecipeNrProperty().setValue(recipeNr);
  }

  public RecipeNrProperty getRecipeNrProperty() {
    return getPropertyByClass(RecipeNrProperty.class);
  }

  public static class Ingredient extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Measure extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Quantity extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class RecipeIngredientNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class RecipeNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
