package ch.pproject.cookbook.shared.recipe;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.recipe.RecipesTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RecipesTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public RecipesTableRowData addRow() {
    return (RecipesTableRowData) super.addRow();
  }

  @Override
  public RecipesTableRowData addRow(int rowState) {
    return (RecipesTableRowData) super.addRow(rowState);
  }

  @Override
  public RecipesTableRowData createRow() {
    return new RecipesTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return RecipesTableRowData.class;
  }

  @Override
  public RecipesTableRowData[] getRows() {
    return (RecipesTableRowData[]) super.getRows();
  }

  @Override
  public RecipesTableRowData rowAt(int index) {
    return (RecipesTableRowData) super.rowAt(index);
  }

  public void setRows(RecipesTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class RecipesTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String recipeNr = "recipeNr";
    public static final String recipeName = "recipeName";
    public static final String preparationTime = "preparationTime";
    public static final String difficulty = "difficulty";
    public static final String portions = "portions";
    private Long m_recipeNr;
    private String m_recipeName;
    private Long m_preparationTime;
    private Long m_difficulty;
    private Long m_portions;

    public Long getRecipeNr() {
      return m_recipeNr;
    }

    public void setRecipeNr(Long newRecipeNr) {
      m_recipeNr = newRecipeNr;
    }

    public String getRecipeName() {
      return m_recipeName;
    }

    public void setRecipeName(String newRecipeName) {
      m_recipeName = newRecipeName;
    }

    public Long getPreparationTime() {
      return m_preparationTime;
    }

    public void setPreparationTime(Long newPreparationTime) {
      m_preparationTime = newPreparationTime;
    }

    public Long getDifficulty() {
      return m_difficulty;
    }

    public void setDifficulty(Long newDifficulty) {
      m_difficulty = newDifficulty;
    }

    public Long getPortions() {
      return m_portions;
    }

    public void setPortions(Long newPortions) {
      m_portions = newPortions;
    }
  }
}
