package ch.pproject.cookbook.shared.recipe;

import java.util.Set;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.recipe.RecipesSearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RecipesSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Difficulty getDifficulty() {
    return getFieldByClass(Difficulty.class);
  }

  public Filter getFilter() {
    return getFieldByClass(Filter.class);
  }

  public Ingredients getIngredients() {
    return getFieldByClass(Ingredients.class);
  }

  public PreparationTimeFrom getPreparationTimeFrom() {
    return getFieldByClass(PreparationTimeFrom.class);
  }

  public PreparationTimeTo getPreparationTimeTo() {
    return getFieldByClass(PreparationTimeTo.class);
  }

  public RecipeName getRecipeName() {
    return getFieldByClass(RecipeName.class);
  }

  /**
   * access method for property SelectedIngredientNrs.
   */
  public Set<Long> getSelectedIngredientNrs() {
    return getSelectedIngredientNrsProperty().getValue();
  }

  /**
   * access method for property SelectedIngredientNrs.
   */
  public void setSelectedIngredientNrs(Set<Long> selectedIngredientNrs) {
    getSelectedIngredientNrsProperty().setValue(selectedIngredientNrs);
  }

  public SelectedIngredientNrsProperty getSelectedIngredientNrsProperty() {
    return getPropertyByClass(SelectedIngredientNrsProperty.class);
  }

  public SelectedIngredients getSelectedIngredients() {
    return getFieldByClass(SelectedIngredients.class);
  }

  public static class Difficulty extends AbstractValueFieldData<Set<Long>> {

    private static final long serialVersionUID = 1L;
  }

  public static class Filter extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Ingredients extends AbstractValueFieldData<Set<Long>> {

    private static final long serialVersionUID = 1L;
  }

  public static class PreparationTimeFrom extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class PreparationTimeTo extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class RecipeName extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class SelectedIngredientNrsProperty extends AbstractPropertyData<Set<Long>> {

    private static final long serialVersionUID = 1L;
  }

  public static class SelectedIngredients extends AbstractValueFieldData<Set<Long>> {

    private static final long serialVersionUID = 1L;
  }
}
