drop table if exists COOKBOOK.RECIPE;

create table COOKBOOK.RECIPE (
	RECIPE_NR					INT,
	RECIPE_NAME					VARCHAR(250),
	PREPARATION_TIME 			INTEGER,
	DIFFICULTY_UID				BIGINT,
	NOTES						VARCHAR(4000),
    PORTIONS					BIGINT,
	PRIMARY KEY (RECIPE_NR)
);

drop table if exists COOKBOOK.INGREDIENT;

create table COOKBOOK.INGREDIENT (
	INGREDIENT_NR				BIGINT 			NOT NULL,
	INGREDIENT_NAME				VARCHAR(60)		UNIQUE,
	PRIMARY KEY (INGREDIENT_NR)
);

drop table if exists COOKBOOK.RECIPE_INGREDIENT;

create table COOKBOOK.RECIPE_INGREDIENT (
	RECIPE_INGREDIENT_NR		BIGINT          NOT NULL,
	RECIPE_NR					BIGINT 			NOT NULL,
	INGREDIENT_NR				BIGINT 			NOT NULL,
	MEASURE_NR					BIGINT,
	QUANTITY					DOUBLE,
	PRIMARY KEY (RECIPE_INGREDIENT_NR)
);

drop table if exists COOKBOOK.RECIPE_STEP;

create table COOKBOOK.RECIPE_STEP (
	RECIPE_STEP_NR				BIGINT 			NOT NULL,
	RECIPE_NR					BIGINT 			NOT NULL,
	DESCRIPTION					VARCHAR(4000),
	STEP_ORDER					INTEGER			NOT NULL
);


drop table if exists COOKBOOK.MEASURE;

create table  COOKBOOK.MEASURE (
	MEASURE_NR				BIGINT			NOT NULL,
	MEASURE_NAME			VARCHAR(60),
	ACRONYM					VARCHAR(60)		UNIQUE,
    DISPLAY_NAME			VARCHAR(250),
	REFERENCE_MEASURE_NR	BIGINT,
	FACTOR					DOUBLE,
	PRIMARY KEY (MEASURE_NR)
);


drop table if exists COOKBOOK.INGREDIENT_MEASURE;

create table  COOKBOOK.INGREDIENT_MEASURE (
	INGREDIENT_NR		BIGINT			NOT NULL,
	MEASURE_NR			BIGINT			NOT NULL
);
