package ch.pproject.cookbook.shared.measure;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.measure.MeasuresTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class MeasureTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public MeasureTableRowData addRow() {
    return (MeasureTableRowData) super.addRow();
  }

  @Override
  public MeasureTableRowData addRow(int rowState) {
    return (MeasureTableRowData) super.addRow(rowState);
  }

  @Override
  public MeasureTableRowData createRow() {
    return new MeasureTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return MeasureTableRowData.class;
  }

  @Override
  public MeasureTableRowData[] getRows() {
    return (MeasureTableRowData[]) super.getRows();
  }

  @Override
  public MeasureTableRowData rowAt(int index) {
    return (MeasureTableRowData) super.rowAt(index);
  }

  public void setRows(MeasureTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class MeasureTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String measureNr = "measureNr";
    public static final String name = "name";
    public static final String acronym = "acronym";
    public static final String referenceUnit = "referenceUnit";
    public static final String factor = "factor";
    private Long m_measureNr;
    private String m_name;
    private String m_acronym;
    private String m_referenceUnit;
    private BigDecimal m_factor;

    public Long getMeasureNr() {
      return m_measureNr;
    }

    public void setMeasureNr(Long newMeasureNr) {
      m_measureNr = newMeasureNr;
    }

    public String getName() {
      return m_name;
    }

    public void setName(String newName) {
      m_name = newName;
    }

    public String getAcronym() {
      return m_acronym;
    }

    public void setAcronym(String newAcronym) {
      m_acronym = newAcronym;
    }

    public String getReferenceUnit() {
      return m_referenceUnit;
    }

    public void setReferenceUnit(String newReferenceUnit) {
      m_referenceUnit = newReferenceUnit;
    }

    public BigDecimal getFactor() {
      return m_factor;
    }

    public void setFactor(BigDecimal newFactor) {
      m_factor = newFactor;
    }
  }
}
