package ch.pproject.cookbook.shared.measure;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.measure.MeasureForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class MeasureFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Acronym getAcronym() {
    return getFieldByClass(Acronym.class);
  }

  public Factor getFactor() {
    return getFieldByClass(Factor.class);
  }

  /**
   * access method for property MeasureNr.
   */
  public Long getMeasureNr() {
    return getMeasureNrProperty().getValue();
  }

  /**
   * access method for property MeasureNr.
   */
  public void setMeasureNr(Long measureNr) {
    getMeasureNrProperty().setValue(measureNr);
  }

  public MeasureNrProperty getMeasureNrProperty() {
    return getPropertyByClass(MeasureNrProperty.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public RefernceMeasure getRefernceMeasure() {
    return getFieldByClass(RefernceMeasure.class);
  }

  public static class Acronym extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Factor extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class MeasureNrProperty extends AbstractPropertyData<Long> {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class RefernceMeasure extends AbstractValueFieldData<Long> {

    private static final long serialVersionUID = 1L;
  }
}
