package ch.pproject.cookbook.shared.recipe.step;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.pproject.cookbook.client.recipe.step.RecipeStepWizardForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class RecipeStepWizardFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;
}
